In [1]:
import numpy as np
from mlp.layers import ReluLayer
test_inputs = np.array([[0.1, -0.2, 0.3], [-0.4, 0.5, -0.6]])
test_grads_wrt_outputs = np.array([[5., 10., -10.], [-5., 0., 10.]])
test_outputs = np.array(
    [[0.1, 0., 0.3], [0., 0.5, 0.]])
test_grads_wrt_inputs = np.array(
    [[5., 0., -10.], [-0., 0., 0.]])
activation_layer = ReluLayer()
outputs = activation_layer.fprop(test_inputs)
all_correct = True
if not outputs.shape == test_outputs.shape:
    print('ReluLayer.fprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(test_outputs, outputs):
    print('ReluLayer.fprop calculated incorrect outputs.')
    all_correct = False
grads_wrt_inputs = activation_layer.bprop(
    test_inputs, outputs, test_grads_wrt_outputs)
if not grads_wrt_inputs.shape == test_grads_wrt_inputs.shape:
    print('ReluLayer.bprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(grads_wrt_inputs, test_grads_wrt_inputs):
    print('ReluLayer.bprop calculated incorrect gradients with respect to inputs.')
    all_correct = False
if all_correct:
    print('Outputs and gradients calculated correctly for ReluLayer.')
print("outputs", outputs)
print("grads with respect to inputs", grads_wrt_inputs)

Outputs and gradients calculated correctly for ReluLayer.
outputs [[ 0.1  0.   0.3]
 [ 0.   0.5  0. ]]
grads with respect to inputs [[  5.   0. -10.]
 [ -0.   0.   0.]]


In [2]:
from mlp.layers import LeakyReluLayer
test_inputs = np.array([[0.1, -0.2, 0.3], [-0.4, 0.5, -0.6]])
test_grads_wrt_outputs = np.array([[5., 10., -10.], [-5., 0., 10.]])
test_outputs = np.array(
    [[0.1, -0.002, 0.3],
 [-0.004, 0.5, -0.006]])
test_grads_wrt_inputs = np.array(
    [[5., 0.1, -10.], [-0.05, 0., 0.1]])
activation_layer = LeakyReluLayer()
outputs = activation_layer.fprop(test_inputs)
all_correct = True
if not outputs.shape == test_outputs.shape:
    print('LeakyReluLayer.fprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(test_outputs, outputs):
    print('LeakyReluLayer.fprop calculated incorrect outputs.')
    all_correct = False
grads_wrt_inputs = activation_layer.bprop(
    test_inputs, outputs, test_grads_wrt_outputs)
if not grads_wrt_inputs.shape == test_grads_wrt_inputs.shape:
    print('LeakyReluLayer.bprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(grads_wrt_inputs, test_grads_wrt_inputs):
    print('LeakyReluLayer.bprop calculated incorrect gradients with respect to inputs.')
    all_correct = False
if all_correct:
    print('Outputs and gradients calculated correctly for LeakyReluLayer.')
print("outputs", outputs)
print("grads with respect to inputs", grads_wrt_inputs)

Outputs and gradients calculated correctly for LeakyReluLayer.
outputs [[ 0.1   -0.002  0.3  ]
 [-0.004  0.5   -0.006]]
grads with respect to inputs [[  5.     0.1  -10.  ]
 [ -0.05   0.     0.1 ]]


In [3]:
from mlp.layers import ELULayer
test_inputs = np.array([[0.1, -0.2, 0.3], [-0.4, 0.5, -0.6]])
test_grads_wrt_outputs = np.array([[5., 10., -10.], [-5., 0., 10.]])
test_outputs = np.array(
    [[0.1, -0.18126925, 0.3],
 [-0.32967995, 0.5, -0.45118836]])
test_grads_wrt_inputs = np.array(
    [[5., 8.18730753, -10.], [-3.35160023, 0., 5.48811636]])
activation_layer = ELULayer()
outputs = activation_layer.fprop(test_inputs)
all_correct = True
if not outputs.shape == test_outputs.shape:
    print('ELULayer.fprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(np.round(test_outputs, decimals=2), np.round(outputs, decimals=2)):
    print('ELULayer.fprop calculated incorrect outputs.')
    all_correct = False
grads_wrt_inputs = activation_layer.bprop(
    test_inputs, outputs, test_grads_wrt_outputs)
if not grads_wrt_inputs.shape == test_grads_wrt_inputs.shape:
    print('ELULayer.bprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(np.round(grads_wrt_inputs, decimals=2), np.round(test_grads_wrt_inputs, decimals=2)):
    print('ELULayer.bprop calculated incorrect gradients with respect to inputs.')
    all_correct = False
if all_correct:
    print('Outputs and gradients calculated correctly for ELULayer.')
print("outputs", outputs)
print("grads with respect to inputs", grads_wrt_inputs)

Outputs and gradients calculated correctly for ELULayer.
outputs [[ 0.1        -0.18126925  0.3       ]
 [-0.32967995  0.5        -0.45118836]]
grads with respect to inputs [[  5.           8.18730753 -10.        ]
 [ -3.35160023   0.           5.48811636]]


In [4]:
from mlp.layers import SELULayer
test_inputs = np.array([[0.1, -0.2, 0.3], [-0.4, 0.5, -0.6]])
test_grads_wrt_outputs = np.array([[5., 10., -10.], [-5., 0., 10.]])
test_outputs = np.array(
    [[0.10507, -0.31869604, 0.31521],
 [-0.5796223, 0.52535, -0.79325065]])
test_grads_wrt_inputs = np.array(
    [[  5.2535, 14.3941, -10.5070],
 [-5.8924, 0., 9.6487]])
activation_layer = SELULayer()
outputs = activation_layer.fprop(test_inputs)
all_correct = True
if not outputs.shape == test_outputs.shape:
    print('SELULayer.fprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(np.round(test_outputs, decimals=2), np.round(outputs, decimals=2)):
    print('SELULayer.fprop calculated incorrect outputs.')
    all_correct = False
grads_wrt_inputs = activation_layer.bprop(
    test_inputs, outputs, test_grads_wrt_outputs)
if not grads_wrt_inputs.shape == test_grads_wrt_inputs.shape:
    print('SELULayer.bprop returned array with wrong shape.')
    all_correct = False
elif not np.allclose(np.round(grads_wrt_inputs, decimals=2), np.round(test_grads_wrt_inputs, decimals=2)):
    print('SELULayer.bprop calculated incorrect gradients with respect to inputs.')
    all_correct = False
if all_correct:
    print('Outputs and gradients calculated correctly for SELULayer.')
print("outputs", outputs)
print("grads with respect to inputs", grads_wrt_inputs)

Outputs and gradients calculated correctly for SELULayer.
outputs [[ 0.10507    -0.31869604  0.31521   ]
 [-0.5796223   0.52535    -0.79325065]]
grads with respect to inputs [[  5.2535      14.39440265 -10.507     ]
 [ -5.89257006   0.           9.64885665]]
